/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaGUI;

/**
 *
 * @author Byron
 */
public class FichaClinica extends javax.swing.JFrame {

    /**
     * Creates new form FichaClinica
     */
    public FichaClinica() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfHora1 = new javax.swing.JTextField();
        jcbSistemaSalud1 = new javax.swing.JComboBox();
        jtfFechaControl1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtfEspecialidad1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtfNombrePaciente1 = new javax.swing.JTextField();
        jtfDoctor1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtaIngresarI1 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtaObservacionesI1 = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        btnVolver1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ficha Clinica");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jtfHora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 50, -1));

        jcbSistemaSalud1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ">>>Sistema De Salud<<<", "Fonasa", "Isapre", "Particular" }));
        jcbSistemaSalud1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSistemaSalud1ActionPerformed(evt);
            }
        });
        getContentPane().add(jcbSistemaSalud1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 203, -1));

        jtfFechaControl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfFechaControl1ActionPerformed(evt);
            }
        });
        getContentPane().add(jtfFechaControl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 203, -1));

        jLabel11.setText("Especialidad :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));
        getContentPane().add(jtfEspecialidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 203, -1));

        jLabel12.setText("Doctor :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 54, -1));
        getContentPane().add(jtfNombrePaciente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 203, -1));
        getContentPane().add(jtfDoctor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 203, -1));

        jLabel13.setText("Hora :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel14.setText("Fecha De Control :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel15.setText("Sistema de Salud :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel16.setText("Nombre Del Paciente :");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel2.setText("Rut :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 204, -1));

        jButton2.setText("Buscar");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jtaIngresarI1.setColumns(20);
        jtaIngresarI1.setRows(5);
        jScrollPane5.setViewportView(jtaIngresarI1);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jLabel17.setText("Ingrese Tratamiento:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        jtaObservacionesI1.setColumns(20);
        jtaObservacionesI1.setRows(5);
        jScrollPane6.setViewportView(jtaObservacionesI1);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, -1, -1));

        jLabel18.setText("Observaciones:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, -1));

        btnVolver1.setText("Volver");
        btnVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbSistemaSalud1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSistemaSalud1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSistemaSalud1ActionPerformed

    private void jtfFechaControl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfFechaControl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFechaControl1ActionPerformed

    private void btnVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver1ActionPerformed
        // TODO add your handling code here:
        MenuClinica mc =new MenuClinica();
        mc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolver1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FichaClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FichaClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FichaClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FichaClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FichaClinica().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox jcbSistemaSalud1;
    public javax.swing.JTextArea jtaIngresarI1;
    public javax.swing.JTextArea jtaObservacionesI1;
    private javax.swing.JTextField jtfDoctor1;
    private javax.swing.JTextField jtfEspecialidad1;
    private javax.swing.JTextField jtfFechaControl1;
    private javax.swing.JTextField jtfHora1;
    private javax.swing.JTextField jtfNombrePaciente1;
    // End of variables declaration//GEN-END:variables
}
