/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaGUI;

/**
 *
 * @author Byron
 */
public class MantenedorTratamiento extends javax.swing.JFrame {

    /**
     * Creates new form IngresoTratamiento
     */
    public MantenedorTratamiento() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpMantendor = new javax.swing.JTabbedPane();
        jpIngrese = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtRutI = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnBuscarI = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaIngresarI = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtaObservacionesI = new javax.swing.JTextArea();
        txtNombreI = new javax.swing.JTextField();
        btnVolverI = new javax.swing.JButton();
        jpModificar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtModificar = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        txtNombreM = new javax.swing.JTextField();
        txtRut = new javax.swing.JTextField();
        btnBuscarM = new javax.swing.JButton();
        btnVolverM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mantenedor Tratamiento");

        jpIngrese.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese Tratamientos"));

        jLabel1.setText("Rut   :");

        jLabel7.setText("Nombre Paciente :");

        jLabel8.setText("Ingrese Tratamiento:");

        jLabel9.setText("Observaciones:");

        btnBuscarI.setText("Buscar");

        jtaIngresarI.setColumns(20);
        jtaIngresarI.setRows(5);
        jScrollPane3.setViewportView(jtaIngresarI);

        jtaObservacionesI.setColumns(20);
        jtaObservacionesI.setRows(5);
        jScrollPane4.setViewportView(jtaObservacionesI);

        btnVolverI.setText("Volver");
        btnVolverI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpIngreseLayout = new javax.swing.GroupLayout(jpIngrese);
        jpIngrese.setLayout(jpIngreseLayout);
        jpIngreseLayout.setHorizontalGroup(
            jpIngreseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIngreseLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jpIngreseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addGroup(jpIngreseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jpIngreseLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jpIngreseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpIngreseLayout.createSequentialGroup()
                                    .addComponent(btnVolverI)
                                    .addGap(103, 103, 103))
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jpIngreseLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addGroup(jpIngreseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnBuscarI)
                                .addComponent(txtNombreI)
                                .addComponent(jScrollPane3)
                                .addComponent(txtRutI)))))
                .addContainerGap(370, Short.MAX_VALUE))
        );
        jpIngreseLayout.setVerticalGroup(
            jpIngreseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIngreseLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jpIngreseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRutI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(btnBuscarI)
                .addGap(31, 31, 31)
                .addGroup(jpIngreseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNombreI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jpIngreseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jpIngreseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnVolverI))
        );

        jtpMantendor.addTab("Ingresar Tratamiento", jpIngrese);

        jpModificar.setBorder(javax.swing.BorderFactory.createTitledBorder("Modifique Tratamiento"));
        jpModificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Rut :");
        jpModificar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel4.setText("Nombre Paciente :");
        jpModificar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel5.setText("Modificar Tratamiento:");
        jpModificar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel6.setText("Observaciones:");
        jpModificar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        txtModificar.setColumns(20);
        txtModificar.setRows(5);
        jScrollPane1.setViewportView(txtModificar);

        jpModificar.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 150, -1, -1));

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane2.setViewportView(txtObservaciones);

        jpModificar.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 273, -1, -1));
        jpModificar.add(txtNombreM, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 106, 166, -1));
        jpModificar.add(txtRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 160, -1));

        btnBuscarM.setText("Buscar");
        jpModificar.add(btnBuscarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 80, -1));

        btnVolverM.setText("Volver");
        btnVolverM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMActionPerformed(evt);
            }
        });
        jpModificar.add(btnVolverM, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 90, 30));

        jtpMantendor.addTab("Modificar Tratamiento", jpModificar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpMantendor)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpMantendor, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverIActionPerformed
        // TODO add your handling code here:
        MenuClinica mc = new MenuClinica();
        mc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverIActionPerformed

    private void btnVolverMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMActionPerformed
        MenuClinica mc = new MenuClinica();
        mc.setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_btnVolverMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenedorTratamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenedorTratamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenedorTratamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenedorTratamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenedorTratamiento().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarI;
    public javax.swing.JButton btnBuscarM;
    public javax.swing.JButton btnVolverI;
    public javax.swing.JButton btnVolverM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JPanel jpIngrese;
    public javax.swing.JPanel jpModificar;
    public javax.swing.JTextArea jtaIngresarI;
    public javax.swing.JTextArea jtaObservacionesI;
    public javax.swing.JTabbedPane jtpMantendor;
    public javax.swing.JTextArea txtModificar;
    public javax.swing.JTextField txtNombreI;
    public javax.swing.JTextField txtNombreM;
    public javax.swing.JTextArea txtObservaciones;
    public javax.swing.JTextField txtRut;
    public javax.swing.JTextField txtRutI;
    // End of variables declaration//GEN-END:variables
}
