/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaGUI;

import javax.swing.JOptionPane;

/**
 *
 * @author Byron
 */
public class MantenedorPaciente extends javax.swing.JFrame {

    /**
     * Creates new form IngresarPaciente
     */
    String nomP,SistemaSalud,FechaControl,hora,Doctor,Especialidad,Tratamiento ;
    public MantenedorPaciente() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaciente = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfNombrePaciente = new javax.swing.JTextField();
        jtfFechaControl = new javax.swing.JTextField();
        jtfHora = new javax.swing.JTextField();
        jtfDoctor = new javax.swing.JTextField();
        jtfEspecialidad = new javax.swing.JTextField();
        jcbSistemaSalud = new javax.swing.JComboBox();
        jbtLimpiar = new javax.swing.JButton();
        jbtSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfRutPaciente = new javax.swing.JTextField();
        jbtBuscar = new javax.swing.JButton();
        jbtAceptar = new javax.swing.JButton();
        jbtVolver = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mantenedor Paciente");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPaciente.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Pacientes"));
        jPaciente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre Del Paciente :");
        jPaciente.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 40, -1, -1));

        jLabel3.setText("Sistema de Salud :");
        jPaciente.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 70, -1, -1));

        jLabel4.setText("Fecha De Control :");
        jPaciente.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 108, -1, -1));

        jLabel5.setText("Hora :");
        jPaciente.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 142, -1, -1));

        jLabel6.setText("Doctor :");
        jPaciente.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 178, 54, -1));

        jLabel7.setText("Especialidad :");
        jPaciente.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 216, -1, -1));
        jPaciente.add(jtfNombrePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 34, 203, -1));

        jtfFechaControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfFechaControlActionPerformed(evt);
            }
        });
        jPaciente.add(jtfFechaControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 105, 203, -1));
        jPaciente.add(jtfHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 139, 50, -1));
        jPaciente.add(jtfDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 175, 203, -1));
        jPaciente.add(jtfEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 213, 203, -1));

        jcbSistemaSalud.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ">>>Sistema De Salud<<<", "Fonasa", "Isapre", "Particular" }));
        jcbSistemaSalud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSistemaSaludActionPerformed(evt);
            }
        });
        jPaciente.add(jcbSistemaSalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 67, 203, -1));

        getContentPane().add(jPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 470, 250));

        jbtLimpiar.setText("Limpiar");
        jbtLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 110, -1));

        jbtSalir.setText("Salir");
        jbtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbtSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, 110, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda Rut Paciente"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Rut Paciente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 42, -1, -1));

        jtfRutPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfRutPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(jtfRutPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 39, 216, -1));

        jbtBuscar.setText("Buscar ");
        jbtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 77, 101, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 470, 120));

        jbtAceptar.setText("Aceptar");
        jbtAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 110, -1));

        jbtVolver.setText("Volver");
        jbtVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jbtVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 101, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mantenedor Paciente.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfFechaControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfFechaControlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFechaControlActionPerformed

    private void jcbSistemaSaludActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSistemaSaludActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSistemaSaludActionPerformed

    private void jtfRutPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfRutPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfRutPacienteActionPerformed

    private void jbtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscarActionPerformed
        // TODO add your handling code here:
       
          

    }//GEN-LAST:event_jbtBuscarActionPerformed

    private void jbtVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVolverActionPerformed
        // TODO add your handling code here:
       MenuClinica mh=new MenuClinica();
       mh.setVisible(true);
       this.setVisible(false);
       
    }//GEN-LAST:event_jbtVolverActionPerformed

    private void jbtLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLimpiarActionPerformed
        // TODO add your handling code here:
        jtfRutPaciente.setText(null);
        jtfNombrePaciente.setText(null);
        jtfFechaControl.setText(null);
        jtfHora.setText(null);
        jtfDoctor.setText(null);
        jtfEspecialidad.setText(null);
        jtfRutPaciente.requestFocus();
      
    }//GEN-LAST:event_jbtLimpiarActionPerformed

    private void jbtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalirActionPerformed
        int seleccion =  JOptionPane.showConfirmDialog(null,"¿Desea salir del sistema?","Salir",JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        switch (seleccion)
        {
            case JOptionPane.YES_OPTION:
            System.exit(0);
            break;

            case JOptionPane.NO_OPTION:
            this.setVisible(true);

            break;

        }     System.exit(0);
    }//GEN-LAST:event_jbtSalirActionPerformed

    private void jbtAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAceptarActionPerformed
        nomP=jtfNombrePaciente.getText();
        SistemaSalud= jcbSistemaSalud.getSelectedItem().toString();
        FechaControl=jtfFechaControl.getText();
        hora=jtfHora.getText();
        Doctor=jtfDoctor.getText();
        Especialidad=jtfEspecialidad.getText();
    }//GEN-LAST:event_jbtAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenedorPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenedorPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenedorPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenedorPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenedorPaciente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPaciente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtAceptar;
    private javax.swing.JButton jbtBuscar;
    private javax.swing.JButton jbtLimpiar;
    private javax.swing.JButton jbtSalir;
    private javax.swing.JButton jbtVolver;
    private javax.swing.JComboBox jcbSistemaSalud;
    private javax.swing.JTextField jtfDoctor;
    private javax.swing.JTextField jtfEspecialidad;
    private javax.swing.JTextField jtfFechaControl;
    private javax.swing.JTextField jtfHora;
    private javax.swing.JTextField jtfNombrePaciente;
    private javax.swing.JTextField jtfRutPaciente;
    // End of variables declaration//GEN-END:variables
}
