/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaGUI;



import CapaDatos.Datos;
import CapaNegocio.NegocioPaciente;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import CapaConexion.Conexion;
/**
 *
 * @author Byron
 */
public class MantenedorPaciente extends javax.swing.JFrame {

    /**
     * Creates new form IngresarPaciente
     */
     private Conexion cnn;
    public MantenedorPaciente() {
        initComponents();
       
       this.cnn=new Conexion();
        this.setLocationRelativeTo(null);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtLimpiar = new javax.swing.JButton();
        jbtSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtRutPaciente = new javax.swing.JTextField();
        jbtBuscar = new javax.swing.JButton();
        jbtVolver = new javax.swing.JButton();
        jbtGuardar = new javax.swing.JButton();
        jPaciente = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombrePaciente = new javax.swing.JTextField();
        txtHoraPaciente = new javax.swing.JTextField();
        cmbSexoPaciente = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEdadPaciente = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmbSistemaSalud = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        cmbTipoSalud = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtFechaControl = new javax.swing.JTextField();
        cmbAtencion = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        cmbCirugia = new javax.swing.JComboBox();
        cmbEspecialidad = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mantenedor Paciente");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtLimpiar.setText("Limpiar");
        jbtLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 430, 110, 30));

        jbtSalir.setText("Salir");
        jbtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbtSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 110, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda Rut Paciente"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Rut Paciente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 42, -1, -1));

        txtRutPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtRutPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 39, 240, -1));

        jbtBuscar.setText("Buscar Rut ");
        jbtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 101, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 430, 120));

        jbtVolver.setText("Volver");
        jbtVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jbtVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 101, -1));

        jbtGuardar.setText("Guardar Información");
        jbtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 150, 30));

        jPaciente.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Pacientes"));
        jPaciente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre Del Paciente :");
        jPaciente.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 160, -1));

        jLabel5.setText("Hora de Atencion :");
        jPaciente.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 100, -1));
        jPaciente.add(txtNombrePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 203, -1));
        jPaciente.add(txtHoraPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 50, -1));

        cmbSexoPaciente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<<Seleccione>>", "Masculino", "Femenino" }));
        jPaciente.add(cmbSexoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 203, -1));

        jLabel10.setText("Sexo Paciente:");
        jPaciente.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 90, -1));

        jLabel8.setText("Edad Paciente :");
        jPaciente.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 250, -1));

        txtEdadPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadPacienteActionPerformed(evt);
            }
        });
        jPaciente.add(txtEdadPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 200, -1));

        getContentPane().add(jPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 530, 180));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Sistema Salud"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Nombre Sistema de salud: ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 160, 10));

        cmbSistemaSalud.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ">>>Seleccione<<<", "Banmedica", "Golden Cross", "Mega Salud", "Cruz Blanca", "Otro" }));
        cmbSistemaSalud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSistemaSaludActionPerformed(evt);
            }
        });
        jPanel2.add(cmbSistemaSalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 140, -1));

        jLabel11.setText("Tipo de Sistema de salud:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, -1));

        cmbTipoSalud.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ">>>Seleccione<<<", "Fonasa", "Isapre", "Particular" }));
        cmbTipoSalud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoSaludActionPerformed(evt);
            }
        });
        jPanel2.add(cmbTipoSalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 140, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 400, 180));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Atencion"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Fecha De Control :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, 20));

        jLabel12.setText("Tipo Atención :");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, -1));
        jPanel3.add(txtFechaControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 203, -1));

        cmbAtencion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<<Seleccione>>", "Funcionario del hospital", "No Funcionario" }));
        jPanel3.add(cmbAtencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 200, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 520, 150));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Especialidad"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbCirugia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<<Seleccione>>", "Ambulatoria", "Operación e Internado" }));
        jPanel4.add(cmbCirugia, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 200, -1));

        cmbEspecialidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<<Seleccione Especialidad>>", "Cirujano", "Neurologo", "Kinesiologo", "Urologo", "Ginecologo", "Traumatologo", "Medicina General", "Medicina Interna", "Odontologia", "Otorrino", "Dermatologia", "Cardiologia", "FonoAudiologo", "Gastroenterologo", "Infectologia Infantil", "Neonatologia", "Nutricionista" }));
        jPanel4.add(cmbEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 200, -1));

        jLabel7.setText("Especialidad :");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 160, -1));

        jLabel13.setText("Tipo Cirugía :");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 520, 140));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mantenedor Paciente1.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSistemaSaludActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSistemaSaludActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSistemaSaludActionPerformed

    private void txtRutPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutPacienteActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_txtRutPacienteActionPerformed

    private void jbtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscarActionPerformed
        // TODO add your handling code here:
        buscarPaciente();
       
        
        
        
        
    }//GEN-LAST:event_jbtBuscarActionPerformed

    private void jbtVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVolverActionPerformed
        // TODO add your handling code here:
       MenuClinica mh=new MenuClinica();
       mh.setVisible(true);
       this.setVisible(false);
       
    }//GEN-LAST:event_jbtVolverActionPerformed

    public void buscarPaciente(){
       if (this.txtRutPaciente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe ingresar un Rut para buscar",
                    "Error de Búsqueda",
                    JOptionPane.ERROR_MESSAGE);
            this.txtRutPaciente.requestFocus();
            return;
        }
        int RutPaciente = Integer.parseInt(this.txtRutPaciente.getText());
        NegocioPaciente negP = new NegocioPaciente();
        Datos Paciente = negP.buscarDatos(RutPaciente);
        
        
         
        
            
        
        if (Paciente.getRutPaciente()!= 0 ) {
            this.txtRutPaciente.setText((String.valueOf(Paciente.getRutPaciente())));// este es el entero verificador
            this.txtNombrePaciente.setText(Paciente.getNombrePaciente());
            this.txtEdadPaciente.setText(Paciente.getEdadPaciente());
            this.txtHoraPaciente.setText(Paciente.getHoraPaciente());
            this.cmbSexoPaciente.setSelectedItem(Paciente.getSexoPaciente());
            this.txtFechaControl.setText(Paciente.getFechaAtencion());
            
        
            this.cmbSistemaSalud.setSelectedItem(Paciente.getNombreSistemaSalud());
            this.cmbTipoSalud.setSelectedItem(Paciente.getTipoSistemaSalud());
              txtRutPaciente.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Este Rut no está registrado",
                    "Error de Búsqueda",
                    JOptionPane.ERROR_MESSAGE);

        }
        
    
    }
    
   
    private void jbtLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLimpiarActionPerformed
        // TODO add your handling code here:
        txtRutPaciente.setText(null);
        txtNombrePaciente.setText(null);
        txtFechaControl.setText(null);
        txtHoraPaciente.setText(null);
        txtFechaControl.setText(null);
        txtEdadPaciente.setText(null);
        cmbAtencion.setSelectedIndex(0);
        cmbCirugia.setSelectedIndex(0);
        cmbSexoPaciente.setSelectedIndex(0);
        cmbSistemaSalud.setSelectedIndex(0);
        cmbTipoSalud.setSelectedIndex(0);
        cmbEspecialidad.setSelectedIndex(0);
        txtEdadPaciente.setText(null);
        txtFechaControl.setText(null);
        txtHoraPaciente.setText(null);
        txtNombrePaciente.setText(null);
        
                
       
        txtRutPaciente.requestFocus();
      
    }//GEN-LAST:event_jbtLimpiarActionPerformed

    private void jbtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalirActionPerformed
        int seleccion =  JOptionPane.showConfirmDialog(null,"¿Desea salir del sistema?","Salir",JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        switch (seleccion)
        {
            case JOptionPane.YES_OPTION:
            System.exit(0);
            break;

            case JOptionPane.NO_OPTION:
            this.setVisible(true);

            break;

        }     System.exit(0);
    }//GEN-LAST:event_jbtSalirActionPerformed

    private void jbtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGuardarActionPerformed
        
        if (this.txtRutPaciente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Ingresar Rut del Paciente",
                    "Error de Ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.txtRutPaciente.requestFocus();
            return;
        }
        
         if (this.txtNombrePaciente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Ingresar El nombre del Paciente",
                    "Error de Ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.txtNombrePaciente.requestFocus();
            return;
        }
        if (this.txtFechaControl.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Ingresar la Fecha de Control",
                    "Error de Ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.txtFechaControl.requestFocus();
            return;
        }
        if (this.txtHoraPaciente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Ingresar la Hora del Paciente",
                    "Error de Ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.txtHoraPaciente.requestFocus();
            return;
        }
        if (this.txtEdadPaciente.getText().isEmpty())  {
            JOptionPane.showMessageDialog(this,
                    "Ingresar La Edad del paciente",
                    "Error de Ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.txtEdadPaciente.requestFocus();
            return;
        }
        if (this.cmbSexoPaciente.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Debe Seleccionar el sexo del paciente",
                    "Error de Ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.cmbSexoPaciente.requestFocus();
            return;
        }
        if (this.cmbCirugia.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Debe Seleccionar la cirugia del paciente",
                    "Error de Ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.cmbCirugia.requestFocus();
            return;
        }
        if (this.cmbAtencion.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Debe Seleccionar una el tipo atencion",
                    "Error de Ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.cmbAtencion.requestFocus();
            return;
        }
        if (this.cmbEspecialidad.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Debe Seleccionar un la especialidad deribada",
                    "Error de Ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.cmbEspecialidad.requestFocus();
            return;
        }
        if (this.cmbSistemaSalud.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Debe Seleccionar un sistema de salud",
                    "Error de Ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.cmbSistemaSalud.requestFocus();
            return;
        }
        
         if (this.cmbTipoSalud.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Debe Seleccionar un tipo sistema de salud",
                    "Error de Ingreso",
                    JOptionPane.ERROR_MESSAGE);
            this.cmbTipoSalud.requestFocus();
            return;
        }
        
        //////////////SQL QUERY////////////////////
    
            
        NegocioPaciente neg = new NegocioPaciente();
        
        //////////////Instancia a la Clase get and setter////////////////////
        Datos Pac=new Datos();
      
        
     
         // ingreso pacientes --con esto obtengo todo lo ingresado en las cajas de textos 
        Pac.setRutPaciente(Integer.parseInt(this.txtRutPaciente.getText()));
        Pac.setNombrePaciente(this.txtNombrePaciente.getText());
        Pac.setEdadPaciente(this.txtEdadPaciente.getText());
        Pac.setSexoPaciente(this.cmbSexoPaciente.getSelectedItem().toString()); 
        Pac.setHoraPaciente(this.txtHoraPaciente.getText());
        Pac.setTipoAtencion(this.cmbAtencion.getSelectedItem().toString());
        Pac.setFechaAtencion(this.txtFechaControl.getText());
        Pac.setTipoSistemaSalud(this.cmbTipoSalud.getSelectedItem().toString());
        Pac.setNombreSistemaSalud(this.cmbSistemaSalud.getSelectedItem().toString());
        Pac.setTipoCirugia(this.cmbCirugia.getSelectedItem().toString());
        Pac.setNombreEspecialidad(this.cmbEspecialidad.getSelectedItem().toString());
        neg.ingresoPaciente(Pac);
      
    
        JOptionPane.showMessageDialog(rootPane, "Se Agrego Satisfactoriamente");
    }//GEN-LAST:event_jbtGuardarActionPerformed

    private void txtEdadPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadPacienteActionPerformed

    private void cmbTipoSaludActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoSaludActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoSaludActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenedorPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenedorPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenedorPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenedorPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenedorPaciente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbAtencion;
    private javax.swing.JComboBox cmbCirugia;
    private javax.swing.JComboBox cmbEspecialidad;
    private javax.swing.JComboBox cmbSexoPaciente;
    private javax.swing.JComboBox cmbSistemaSalud;
    private javax.swing.JComboBox cmbTipoSalud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPaciente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbtBuscar;
    private javax.swing.JButton jbtGuardar;
    private javax.swing.JButton jbtLimpiar;
    private javax.swing.JButton jbtSalir;
    private javax.swing.JButton jbtVolver;
    private javax.swing.JTextField txtEdadPaciente;
    private javax.swing.JTextField txtFechaControl;
    private javax.swing.JTextField txtHoraPaciente;
    private javax.swing.JTextField txtNombrePaciente;
    private javax.swing.JTextField txtRutPaciente;
    // End of variables declaration//GEN-END:variables
}
