/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaGUI;

/**
 *
 * @author Byron
 */
public class MenuClinica extends javax.swing.JFrame {

    /**
     * Creates new form MenuHospital
     */
    public MenuClinica() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmOpciones = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jmiIngresarPaciente = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jmDefinirTratamiento = new javax.swing.JMenu();
        jmiIngresoTra = new javax.swing.JMenuItem();
        jmiModificarTra = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiConsultaFicha = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiIngresarDoc = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Hospital");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 73, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Bienvenido Al Menu");
        jLabel1.setName(""); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 70, 200, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuPaciente.jpg"))); // NOI18N
        jLabel3.setText("Menu Hospital");
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 290));

        jmOpciones.setText("Mantenedor Pacientes");

        jMenu3.setText("Gestion de Pacientes");

        jmiIngresarPaciente.setText("Ingresar Paciente");
        jmiIngresarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiIngresarPacienteActionPerformed(evt);
            }
        });
        jMenu3.add(jmiIngresarPaciente);

        jMenuItem2.setText("Modificar Ficha Paciente");
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Cambiar Hora Del Paciente");
        jMenu3.add(jMenuItem3);

        jmOpciones.add(jMenu3);

        jmDefinirTratamiento.setText("Definir Tratamiento");

        jmiIngresoTra.setText("Ingreso Tratamiento");
        jmDefinirTratamiento.add(jmiIngresoTra);

        jmiModificarTra.setText("Modificar Tratamiento");
        jmDefinirTratamiento.add(jmiModificarTra);

        jmOpciones.add(jmDefinirTratamiento);

        jMenu4.setText("Consultas de Fichas");

        jmiConsultaFicha.setText("Ficha Paciente");
        jMenu4.add(jmiConsultaFicha);

        jmOpciones.add(jMenu4);

        jMenuBar1.add(jmOpciones);

        jMenu2.setText("Mantenedor Doctores");

        jmiIngresarDoc.setText("Actualizar Informacion de Doctores");
        jmiIngresarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiIngresarDocActionPerformed(evt);
            }
        });
        jMenu2.add(jmiIngresarDoc);

        jMenuItem5.setText("Consultar Informacion de Doctores");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiIngresarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiIngresarDocActionPerformed
        // TODO add your handling code here:
        IngresarDoctores ID=new IngresarDoctores();
        ID.setVisible(true);
        
    }//GEN-LAST:event_jmiIngresarDocActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        MostrarDoctor md =new MostrarDoctor();
        md.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        Principal pri=new Principal();
        pri.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jmiIngresarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiIngresarPacienteActionPerformed
        // TODO add your handling code here:
        MantenedorPaciente ip=new MantenedorPaciente();
        ip.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jmiIngresarPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuClinica().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenu jmDefinirTratamiento;
    private javax.swing.JMenu jmOpciones;
    private javax.swing.JMenuItem jmiConsultaFicha;
    private javax.swing.JMenuItem jmiIngresarDoc;
    private javax.swing.JMenuItem jmiIngresarPaciente;
    private javax.swing.JMenuItem jmiIngresoTra;
    private javax.swing.JMenuItem jmiModificarTra;
    // End of variables declaration//GEN-END:variables
}
